# Generated by Django 5.2.3 on 2025-10-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_event_category_event_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Conference'), ('podcast', 'Live Podcast'), ('workshop', 'Workshop'), ('schools', 'Seasonal Schools'), ('courses', 'Courses/Retreats'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
