# Generated by Django 5.2.3 on 2026-03-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Application deadline for this event', null=True),
        ),
    ]
