# Generated by Django 5.2.3 on 2026-07-27 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_deadline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for administrators'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
