# Generated by Django 5.2.3 on 2026-09-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_is_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_url',
            field=models.URLField(blank=True, help_text='Link to the application or registration page for this event'),
        ),
    ]
