# Generated by Django 5.2.3 on 2026-09-10 23:34

from django.db import migrations, models


def podcast_to_other(apps, schema_editor):
    """Re-point any existing 'Live Podcast' events to 'Other'.

    The category is being removed from the site entirely. This mapping is
    lossy -- there is no way to tell afterwards that a row used to be a
    podcast -- so the reverse is a no-op.
    """
    Event = apps.get_model('events', 'Event')
    Event.objects.filter(category='podcast').update(category='other')


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_application_url'),
    ]

    operations = [
        migrations.RunPython(podcast_to_other, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('conference', 'Conference'), ('workshop', 'Workshop'), ('schools', 'Seasonal Schools'), ('courses', 'Courses/Retreats'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
