# Generated by Django 5.2.3 on 2026-07-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_countries_job_is_for_graduate_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_for_graduate_students',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
