# Generated by Django 5.2.3 on 2026-07-27 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def approve_existing_jobs(apps, schema_editor):
    """Grandfather jobs that predate moderation so they stay publicly visible."""
    Job = apps.get_model('jobs', 'Job')
    Job.objects.update(status='approved')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_options_job_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for administrators'),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.RunPython(approve_existing_jobs, noop),
    ]
