# Generated by Django 5.2.3 on 2026-08-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_admin_notes_job_reviewed_at_job_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_example',
            field=models.BooleanField(default=False, help_text="Illustrative content seeded for testing, not a real submission. Shown publicly with an 'Example' badge and removable in one step via `manage.py seed_examples --remove`."),
        ),
    ]
