# Generated by Django 5.2.3 on 2026-09-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_is_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employer',
            field=models.CharField(blank=True, help_text='Hiring institution or organization', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='pay',
            field=models.CharField(blank=True, help_text='e.g. "$70,000–85,000 / year" or "Competitive". Optional.', max_length=255),
        ),
    ]
