# Generated by Django 5.2.3 on 2026-09-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='admin1_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='core_city_name_079295_idx'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['latitude', 'longitude'], name='core_city_latitud_bcc695_idx'),
        ),
    ]
