# Generated by Django 5.2.3 on 2025-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_avatar'),
    ]

    # No-op on purpose: the initial migration now creates research_interests as a
    # backend-agnostic JSONField directly, so the former PostgreSQL-only jsonb
    # conversion is unnecessary. Kept (empty) to preserve migration history and any
    # existing PostgreSQL databases where it was already applied.
    operations = []
