# Generated by Django 5.2.3 on 2025-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research_interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
