# Generated by Django 5.2.3 on 2025-09-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_avatar'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE accounts_profile
            ALTER
            COLUMN research_interests
                TYPE jsonb
                USING to_jsonb(research_interests);
            """,
            reverse_sql="""
                        ALTER TABLE accounts_profile
                        ALTER
                        COLUMN research_interests
                TYPE varchar[]
                USING array(SELECT jsonb_array_elements_text(research_interests));
                        """
        ),

    ]
