# Generated by Django 5.2.3 on 2025-09-08 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_research_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='resume',
            field=models.FileField(blank=True, help_text='Please upload a copy of your resume. pdf or docx only.', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.FileField(help_text='Upload your research paper in PDF format', upload_to='research_papers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_papers', to='accounts.userapplication')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('paper__endswith', '.pdf')), name='paper_is_pdf')],
            },
        ),
    ]
