# Generated by Django 5.2.3 on 2025-09-08 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userapplication_resume_researchpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
