# Generated by Django 5.2.3 on 2025-09-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userapplication_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
