# Generated by Django 5.2.3 on 2025-09-26 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userapplication_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Select your advisor (required for students)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='user_type',
            field=models.CharField(choices=[('researcher', 'Researcher'), ('student', 'Student')], default='researcher', help_text='Select whether you are applying as a researcher or student', max_length=10),
        ),
    ]
