# Generated by Django 5.2.3 on 2025-09-28 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_userapplication_advisor_userapplication_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplication',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Required for students', limit_choices_to={'role': 'researcher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('researcher', 'Researcher')], default='researcher', max_length=20),
        ),
        migrations.AlterField(
            model_name='userapplication',
            name='advisor',
            field=models.ForeignKey(blank=True, help_text='Only required for student applications', limit_choices_to={'role': 'researcher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
