# Generated by Django 5.2.3 on 2025-09-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userapplication_user_type_customuser_advisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('researcher', 'Researcher')], default='researcher', max_length=255),
        ),
    ]
