# Generated by Django 5.2.3 on 2025-12-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userapplication_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research_interests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
