# Generated by Django 5.2.3 on 2026-07-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_normalize_research_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='digest_frequency',
            field=models.CharField(choices=[('off', 'Off'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='off', help_text='How often to receive an email digest of newly added content.', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
