"""Replace the muddled institution fields with department + affiliation.

`education` was labelled "Current Institution" in every form but in practice held
degree history ("PhD Economics, MIT"), while `position` was labelled "Current
Affiliation" but held a job title. This renames `education` to `department` --
RenameField, so no data is lost -- and adds a proper affiliation as a FK to the
shared University table plus a free-text fallback, mirroring the pair already on
Seminar.

Written by hand rather than autogenerated: makemigrations prompts interactively
for the rename, and answering "no" would drop the column and recreate it empty.
"""

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_profile_digest_frequency_profile_last_digest_sent_at"),
        # The University FK targets seminars; that table must already exist.
        ("seminars", "0006_seminar_is_example"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="education",
            new_name="department",
        ),
        migrations.RenameField(
            model_name="userapplication",
            old_name="education",
            new_name="department",
        ),
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_profiles",
                to="seminars.university",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="university_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="seminars.university",
            ),
        ),
        migrations.AddField(
            model_name="userapplication",
            name="university_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
