# Generated by Django 5.2.3 on 2026-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_department_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
