# Generated by Django 5.2.3 on 2026-09-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userapplication_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='other_networks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
