# Generated by Django 5.2.3 on 2026-09-30 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_merge_comma_split_research_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Or upload a CV as a PDF.', null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_url',
            field=models.URLField(blank=True, help_text='Link to your CV, if you keep one online.'),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='cv_url',
            field=models.URLField(blank=True, help_text='Link to your CV, if you keep one online (optional).'),
        ),
    ]
