# Generated by Django 5.2.3 on 2026-10-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profile_cv_file_profile_cv_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_countries',
            field=models.JSONField(blank=True, default=list, help_text='Get a weekly email when a new visit to one of these countries is posted.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='alert_topics',
            field=models.JSONField(blank=True, default=list, help_text='Get a weekly email when a new paper on one of these topics is posted.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
