# Generated by Django 5.2.3 on 2026-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_profile_alert_countries_profile_alert_topics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_universities',
            field=models.JSONField(blank=True, default=list, help_text='Get a weekly email when a new visit to one of these institutions is posted.'),
        ),
    ]
