# Generated by Django 5.2.3 on 2026-10-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_profile_alert_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deactivation_warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
