# Generated by Django 5.2.3 on 2026-10-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_profile_deactivation_warned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapplication',
            name='previous_jm_paper_number',
            field=models.CharField(blank=True, help_text='Discussion series number of their job market paper, e.g. J3.', max_length=20, verbose_name='Job market paper number'),
        ),
        migrations.AddField(
            model_name='userapplication',
            name='previous_student_account',
            field=models.BooleanField(default=False, verbose_name='Previously had a student account'),
        ),
    ]
