# Generated by Django 5.2.3 on 2025-07-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='sample_size',
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdf'),
        ),
    ]
