# Generated by Django 5.2.3 on 2025-07-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_remove_publication_sample_size_publication_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
