# Generated by Django 5.2.3 on 2025-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_remove_publication_country_publication_country_code'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE publications_publication
            ALTER
            COLUMN keywords
                TYPE jsonb
                USING to_jsonb(keywords);
            """,
            reverse_sql="""
                        ALTER TABLE publications_publication
                        ALTER
                        COLUMN keywords
                TYPE varchar[]
                USING array(SELECT jsonb_array_elements_text(keywords));
                        """
        ),
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
