# Generated by Django 5.2.3 on 2025-09-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_remove_publication_country_publication_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='keywords',
            field=models.JSONField(default=list),
        ),
    ]
