# Generated by Django 5.2.3 on 2025-09-07 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_alter_publication_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='month',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='year',
        ),
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
