# Generated by Django 5.2.3 on 2025-09-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_remove_publication_month_remove_publication_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='topic',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
