# Generated by Django 5.2.3 on 2025-09-08 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_publication_admin_notes_publication_applied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='approved',
        ),
    ]
