# Generated by Django 5.2.3 on 2025-09-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_remove_publication_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='is_job_market',
            field=models.BooleanField(default=False),
        ),
    ]
