# Generated by Django 5.2.3 on 2026-09-10 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_drop_legacy_paper_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='jm_advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'researcher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_job_market_papers', to=settings.AUTH_USER_MODEL, verbose_name='Job market advisor'),
        ),
        migrations.AddField(
            model_name='publication',
            name='jm_advisor_acknowledged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='jm_advisor_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_publications', to=settings.AUTH_USER_MODEL),
        ),
    ]
