# Generated by Django 5.2.3 on 2026-09-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_publication_advisor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='discussion_paper_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf_original',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdf/original'),
        ),
    ]
