# Generated by Django 5.2.3 on 2026-09-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0021_publication_cover_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='job_market_paper_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
