# Generated by Django 5.2.3 on 2026-09-29 17:54, then hand-edited.
#
# Django's autogenerated version of this migration issues a plain CreateModel
# for PublicationAuthor, which -- because its db_table is deliberately the
# SAME table the plain ManyToManyField already auto-created
# (publications_publication_authors) -- would try to CREATE TABLE over an
# existing one and fail on any database that already has publications rows
# (including a fresh `migrate` from scratch, since 0001 already created that
# table for the old field definition).
#
# Fix: split into three steps that only ever touch what's actually new.
#   1. A state-only CreateModel/AlterField that tells Django's migration
#      state about PublicationAuthor (matching the table's current real
#      columns: id, publication_id, author_id) and that `authors` now goes
#      through it -- no database_operations, so nothing is issued against
#      the live database, which already has exactly that shape.
#   2. A plain AddField for `position`, now that the model exists in state --
#      this is the one real schema change, an ALTER TABLE ADD COLUMN.
#   3. A data migration backfilling `position` from each row's existing `id`
#      order, the closest approximation available to the order authors were
#      originally entered in.
import django.db.models.deletion
from django.db import migrations, models


def backfill_position(apps, schema_editor):
    PublicationAuthor = apps.get_model('publications', 'PublicationAuthor')
    for publication_id in (
        PublicationAuthor.objects.order_by()
        .values_list('publication_id', flat=True).distinct()
    ):
        links = PublicationAuthor.objects.filter(
            publication_id=publication_id).order_by('id')
        for position, link in enumerate(links):
            link.position = position
            link.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0022_publication_job_market_paper_number'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='PublicationAuthor',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.author')),
                        ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_links', to='publications.publication')),
                    ],
                    options={
                        'db_table': 'publications_publication_authors',
                        'unique_together': {('publication', 'author')},
                    },
                ),
                migrations.AlterField(
                    model_name='publication',
                    name='authors',
                    field=models.ManyToManyField(related_name='publications', through='publications.PublicationAuthor', to='publications.author'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='publicationauthor',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='publicationauthor',
            options={'ordering': ['position']},
        ),
        migrations.RunPython(backfill_position, migrations.RunPython.noop),
    ]
