# Generated by Django 5.2.3 on 2026-09-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0023_publicationauthor_alter_publication_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='download_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
