# Generated by Django 5.2.3 on 2026-10-08 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0024_publication_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='revision_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='revision_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='publications.publication'),
        ),
    ]
