# Generated by Django 5.2.3 on 2026-03-23 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=255)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='seminars.seminar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('seminar', 'user'), name='unique_seminar_interest_user'), models.UniqueConstraint(condition=models.Q(('guest_email__gt', '')), fields=('seminar', 'guest_email'), name='unique_seminar_interest_guest_email')],
            },
        ),
    ]
