# Generated by Django 5.2.3 on 2026-03-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_seminarinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='location',
        ),
        migrations.AddField(
            model_name='seminar',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
