# Generated by Django 5.2.3 on 2026-09-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0006_seminar_is_example'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
    ]
