# Generated by Django 5.2.3 on 2026-09-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_alter_seminar_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('open', 'Open to extending'), ('long_term', 'Long-term stay')], default='', help_text='How flexible the visit dates are.', max_length=20),
        ),
    ]
