# Generated by Django 5.2.3 on 2026-09-24 02:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators')),
                ('is_example', models.BooleanField(default=False, help_text="Illustrative content seeded for testing, not a real submission. Shown publicly with an 'Example' badge and removable in one step via `manage.py seed_examples --remove`.")),
                ('journal', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Include a link to the call for papers.')),
                ('call_url', models.URLField(blank=True, help_text='Call for papers link')),
                ('submission_deadline', models.DateField()),
                ('editors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_issues', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submission_deadline'],
            },
        ),
    ]
